"""Centralized alerting system for ASAHIO platform.

Sends email alerts for critical errors and operational issues.
Uses Resend for email delivery (configured via RESEND_API_KEY env var).

Alert severity levels:
- CRITICAL: Immediate attention required (data loss, service outage)
- WARNING: Important but not urgent (degraded performance, high error rate)
- INFO: Informational (deployment, configuration changes)

Alert triggers:
- Trace write failures (data loss)
- Background task failures (retry exhaustion)
- Error rate spikes (>10 errors/min)
- Circuit breaker opens (provider outage)

Usage:
    from app.core.alerts import send_alert, AlertSeverity

    await send_alert(
        severity=AlertSeverity.CRITICAL,
        title="Trace write failed",
        message="Failed to write trace for org abc123",
        context={"org_id": "abc123", "error": str(exc)},
    )
"""

import logging
import os
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class AlertChannel(str, Enum):
    """Alert delivery channels."""
    EMAIL = "email"


def _get_alert_email() -> Optional[str]:
    """Get the email address to send alerts to from environment."""
    return os.getenv("ALERT_EMAIL")


def _get_resend_api_key() -> Optional[str]:
    """Get Resend API key from environment."""
    return os.getenv("RESEND_API_KEY")


def _format_email_body(
    severity: AlertSeverity,
    title: str,
    message: str,
    context: dict[str, Any],
    environment: str,
) -> str:
    """Format email body with alert details."""
    severity_emoji = {
        AlertSeverity.CRITICAL: "🚨",
        AlertSeverity.WARNING: "⚠️",
        AlertSeverity.INFO: "ℹ️",
    }

    lines = [
        f"{severity_emoji.get(severity, '')} **{severity.value.upper()}** - {title}",
        "",
        f"**Time:** {datetime.now(timezone.utc).isoformat()}",
        f"**Environment:** {environment}",
        "",
        "## Message",
        message,
        "",
    ]

    if context:
        lines.extend([
            "## Context",
            "```json",
        ])
        import json
        lines.append(json.dumps(context, indent=2, default=str))
        lines.append("```")
        lines.append("")

    lines.extend([
        "---",
        f"*This alert was generated by ASAHIO platform monitoring*",
    ])

    return "\n".join(lines)


async def send_alert(
    severity: AlertSeverity,
    title: str,
    message: str,
    context: Optional[dict[str, Any]] = None,
    channel: AlertChannel = AlertChannel.EMAIL,
) -> bool:
    """Send an alert via the specified channel.

    Args:
        severity: Alert severity (CRITICAL, WARNING, INFO)
        title: Short alert title
        message: Detailed alert message
        context: Additional context (org_id, error, stack trace, etc.)
        channel: Delivery channel (EMAIL only for now)

    Returns:
        True if alert sent successfully, False otherwise

    Example:
        await send_alert(
            severity=AlertSeverity.CRITICAL,
            title="Trace write failed",
            message="Failed to write trace after 3 retries",
            context={
                "org_id": "123e4567-e89b-12d3-a456-426614174000",
                "error": "ConnectionError: Redis unavailable",
                "trace_id": "abc123",
            },
        )
    """
    if channel != AlertChannel.EMAIL:
        logger.warning("Unsupported alert channel: %s", channel)
        return False

    alert_email = _get_alert_email()
    if not alert_email:
        logger.warning(
            "ALERT_EMAIL not configured - alert not sent: %s",
            title,
            extra={
                "severity": severity.value,
                "title": title,
                "skip_reason": "no_email_configured",
            }
        )
        return False

    resend_api_key = _get_resend_api_key()
    if not resend_api_key:
        logger.warning(
            "RESEND_API_KEY not configured - alert not sent: %s",
            title,
            extra={
                "severity": severity.value,
                "title": title,
                "skip_reason": "no_api_key",
            }
        )
        return False

    environment = os.getenv("RAILWAY_ENVIRONMENT", "local")
    body = _format_email_body(
        severity=severity,
        title=title,
        message=message,
        context=context or {},
        environment=environment,
    )

    try:
        import resend
        resend.api_key = resend_api_key

        params = {
            "from": "ASAHIO Alerts <alerts@asahio.in>",
            "to": [alert_email],
            "subject": f"[{severity.value.upper()}] {title}",
            "html": f"<pre>{body}</pre>",
        }

        result = resend.Emails.send(params)

        logger.info(
            "Alert sent successfully",
            extra={
                "severity": severity.value,
                "title": title,
                "email_id": result.get("id"),
            }
        )
        return True

    except Exception as exc:
        logger.error(
            "Failed to send alert email",
            extra={
                "severity": severity.value,
                "title": title,
                "error": str(exc),
            },
            exc_info=True
        )
        return False


async def alert_trace_write_failure(
    org_id: str,
    trace_id: Optional[str],
    error: str,
    stack_trace: Optional[str] = None,
) -> None:
    """Alert on trace write failure (critical data loss).

    Args:
        org_id: Organization ID
        trace_id: Trace ID (if available)
        error: Error message
        stack_trace: Stack trace (if available)
    """
    context = {
        "org_id": org_id,
        "trace_id": trace_id,
        "error": error,
    }
    if stack_trace:
        context["stack_trace"] = stack_trace

    await send_alert(
        severity=AlertSeverity.CRITICAL,
        title="Trace write failed",
        message=f"Failed to write trace for org {org_id}. This is a data loss event.",
        context=context,
    )


async def alert_background_task_failure(
    task_name: str,
    error: str,
    retry_count: int,
    context: Optional[dict[str, Any]] = None,
) -> None:
    """Alert on background task failure after retry exhaustion.

    Args:
        task_name: Name of the task that failed
        error: Error message
        retry_count: Number of retries attempted
        context: Additional context
    """
    alert_context = {
        "task_name": task_name,
        "error": error,
        "retry_count": retry_count,
    }
    if context:
        alert_context.update(context)

    await send_alert(
        severity=AlertSeverity.CRITICAL,
        title=f"Background task failed: {task_name}",
        message=f"Task '{task_name}' failed after {retry_count} retries.",
        context=alert_context,
    )


async def alert_error_rate_spike(
    error_count: int,
    time_window_seconds: int,
    threshold: int,
    sample_errors: list[str],
) -> None:
    """Alert on error rate spike.

    Args:
        error_count: Number of errors in time window
        time_window_seconds: Time window in seconds
        threshold: Threshold that was exceeded
        sample_errors: Sample of recent error messages
    """
    await send_alert(
        severity=AlertSeverity.WARNING,
        title="Error rate spike detected",
        message=f"{error_count} errors in {time_window_seconds}s (threshold: {threshold})",
        context={
            "error_count": error_count,
            "time_window_seconds": time_window_seconds,
            "threshold": threshold,
            "sample_errors": sample_errors[:5],  # First 5 errors
        },
    )


async def alert_circuit_breaker_open(
    provider: str,
    failure_count: int,
    failure_threshold: int,
) -> None:
    """Alert when circuit breaker opens for a provider.

    Args:
        provider: Provider name (openai, anthropic, etc.)
        failure_count: Number of consecutive failures
        failure_threshold: Threshold that triggered the circuit open
    """
    await send_alert(
        severity=AlertSeverity.WARNING,
        title=f"Circuit breaker opened: {provider}",
        message=f"Provider '{provider}' circuit opened after {failure_count} failures.",
        context={
            "provider": provider,
            "failure_count": failure_count,
            "failure_threshold": failure_threshold,
        },
    )
